name: Update database types

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install dependencies
        run: yarn install

      - name: Generate Supabase types
        run: yarn run update-types

      - name: Check for file changes
        id: git_status
        run: |
          echo "status=$(git status -s)" >> $GITHUB_OUTPUT

      - name: Commit files
        if: ${{ contains(steps.git_status.outputs.status, ' ') }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add supabase/types.ts
          git commit -m 'chore: update Supabase types'

      - name: Push changes
        if: ${{ contains(steps.git_status.outputs.status, ' ') }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
